# -*- coding: utf-8 -*-
"""mi_libreria_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okSIDbPukdPhGOAuyZsMqpFjLZ-lbhuh
"""

# prompt: generar una funcion que tome un numero y le sume 1 otra funcion que tome al numero y lo muiltiplque por 3 y otra que haga 1-1/ese numero
import numpy as np


def sumar_uno(numero):
  """Suma 1 al número dado."""
  return numero + 1

def multiplicar_por_tres(numero):
  """Multiplica el número dado por 3."""
  return numero * 3

def uno_menos_inverso(numero):
  """Calcula 1 - 1/numero."""
  if numero == 0:
    return "Indefinido"
  return 1 - (1 / numero)


def matriz_diagonal(n, m):
  """Crea una matriz cuadrada de MxM con N en toda la diagonal."""
  matriz = np.zeros((m, m))
  np.fill_diagonal(matriz, n)
  return matriz

